name: d20
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.4=py39h080aedc_0
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2021.10.8=py39haa95532_2
  - intel-openmp=2021.4.0=haa95532_3556
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - numexpr=2.8.1=py39hb80d3ca_0
  - numpy=1.22.3=py39h7a0a035_0
  - numpy-base=1.22.3=py39hca35cd5_0
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py39hd77b12b_0
  - pendulum=2.1.2=pyhd3eb1b0_1
  - pip=21.2.4=py39haa95532_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.9.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pytzdata=2020.1=pyhd3eb1b0_0
  - setuptools=61.2.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=h2bbff1b_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py39haa95532_2
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.6.1
    - async-timeout==4.0.2
    - attrs==21.4.0
    - charset-normalizer==2.0.12
    - frozenlist==1.3.0
    - h11==0.12.0
    - httpcore==0.14.7
    - httpx==0.22.0
    - idna==3.3
    - multidict==6.0.2
    - orderedmultidict==1.0.1
    - py-cord==2.0.0rc1
    - python-dotenv==0.20.0
    - pyyaml==6.0
    - rfc3986==1.5.0
    - sniffio==1.2.0
    - thefuzz==0.19.0
    - yarl==1.7.2
